service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  # setup profile for AWS CLI.
  profile: default
  environment:
    BUCKET: 'node-in-aws-s3-task5-dzianis'
    TABLE_PRODUCTS: 'products'
    TABLE_STOCKS: 'stocks'
    SQS_URL: 'https://sqs.us-east-1.amazonaws.com/647708977940/catalogItemsQueue.fifo'
#    SQS_ARN: !ImportValue 'CatalogItemsQueueArn'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::node-in-aws-s3-task5-dzianis"
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::node-in-aws-s3-task5-dzianis/*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource:
            - "arn:aws:sqs:us-east-1:647708977940:catalogItemsQueue.fifo"
functions:
  importProductsFile:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: import/{fileName}
          method: get
          cors: true
  importFileParser:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: node-in-aws-s3-task5-dzianis
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true